### PR TITLE
Add more legume species

### PR DESCRIPTION
**Pull request by svengato**
See issue #42

### CODE REVIEW

**Review by alancleary — APPROVED** [review]
The code looks good and all tests pass.

Regarding haggling about color choices, I don't know historically how colors were selected for new genera so unless @adf-ncgr wants to weigh in I think these colors are fine.

**Comment by svengato** [comment]
@adf-ncgr: this is your opportunity to say "Teal for that, you must be mad!"

**Comment by adf-ncgr** [comment]
That's a nice gourd.

**Comment by svengato** [comment]
"It's under offer."

**Comment by svengato** [comment]
Merging - we can always change the colors later.

**Pull request merged**
