### PR TITLE
Convert library to Typescript and prepare for publication on NPM

### PR DESCRIPTION
**Pull request by alancleary**
This isn't actually published on NPM yet so you'll have to test by cloning the repo and building it yourself. `npm run build` and `npm run bundle` should do the trick.

@svengato Can you try using this with Funnotate? Gotta make sure it's actually gonna work where we use it! I'll make sure it works with GCV.

### CODE REVIEW

**Comment by svengato** [comment]
Note to self: this is to replace the hard-coded genus and taxon colors in Funnotate `static/js/phylogram.js`.

**Comment by svengato** [comment]
Had to install npm and typescript first,
```
sudo dnf install nodejs
sudo npm install typescript -g
```

Then `npm run build` cannot find `chroma.ts`.
```
src/index.ts:24:25 - error TS2307: Cannot find module 'chroma.ts' or its corresponding type declarations.
```
Now looking for that.

**Comment by svengato** [comment]
`npm install chroma.ts` installed it.

Then
```
npm run build
npm run bundle
```
generates `dist/taxon-symbology.min.js`.

**Comment by alancleary** [comment]
> `npm install chroma.ts` installed it.
> 
> Then
> 
> ```
> npm run build
> npm run bundle
> ```
> 
> generates `dist/taxon-symbology.min.js`.

You don't have to install the dependencies manually. Just clone the repo and run `npm install`.

**Comment by svengato** [comment]
> You don't have to install the dependencies manually. Just clone the repo and run npm install.

From within the repository? Do I need to delete the directory and start over?

**Comment by alancleary** [comment]
> > You don't have to install the dependencies manually. Just clone the repo and run npm install.
> 
> From within the repository? Do I need to delete the directory and start over?

No. Just delete the `node_modules/` directory if you want to be sure everything gets installed correctly.

The Node.js [intro to NPM](https://nodejs.org/en/learn/getting-started/an-introduction-to-the-npm-package-manager) post might be worth a read.

**Comment by svengato** [comment]
`npm install` creates a `dist/taxon-symbology.min.js` identical to the one I had before. I can copy this to Funnotate's common js directory and import the module from there (if I redeclare the importing javascript file as a "module"), and the taxon colors (at least the few I tested) are the same as before, but this causes other conflicts with Shiny. I will experiment with some other import methods.

**Comment by alancleary** [comment]
> `npm install` creates a `dist/taxon-symbology.min.js` identical to the one I had before. I can copy this to Funnotate's common js directory and import the module from there (if I redeclare the importing javascript file as a "module"), and the taxon colors (at least the few I tested) are the same as before, but this causes other conflicts with Shiny. I will experiment with some other import methods.

ECMAScript modules are the official/recommended way of packaging JavaScript code now days so that's why this TypeScript code generates an ECMAScript module even though the pre-existing JavaScript code was a CommonJS module.

One workaround is to just assign to `taxonChroma` object to a global variable after importing it:
```html
<script type="module">
    import { taxonChroma } from 'node_modules/@legumeinfo/taxon-symbology/dist/taxon-symbology.min.js';
    window.taxonChroma = taxonChroma;
</script>
```

**Comment by svengato** [comment]
After some experimentation,
1. `import { taxonChroma } ...` needs to be in its own module, separate from phylogram.js which is regular JavaScript, otherwise there are conflicts with shinyjs. Still figuring out how to get taxonChroma (or window.taxonChroma) into phylogram.js so I can use it.
2. Taxon names to override must be in lower case, which is okay. Maybe just add a comment to that effect in the README.

**Comment by alancleary** [comment]
> After some experimentation,
> 
> 1. `import { taxonChroma } ...` needs to be in its own module, separate from phylogram.js which is regular JavaScript, otherwise there are conflicts with shinyjs. Still figuring out how to get taxonChroma (or window.taxonChroma) into phylogram.js so I can use it.

Just do the `window.taxonChroma = chroma` workaround before importing phylogram.js. This way `taxonChroma` will be in the global scope by the time phylogram.js needs it.

> 2. Taxon names to override must be in lower case, which is okay. Maybe just add a comment to that effect in the README.

This was the existing functionality. It's probably worth making the override consistent with non-overridden coloring, i.e. your input can be any case and it will be cast to lower-case internally. What do you think?

**Comment by svengato** [comment]
> Just do the window.taxonChroma = chroma workaround before importing phylogram.js. This way taxonChroma will be in the global scope by the time phylogram.js needs it.

In my `ui.R`, `taxon-symbology-module.js` (which imports `taxonChroma` from `taxon-symbology.min.js`) goes before `phylogram.js`, but for some reason it does not work. (Maybe lazy loading?) I will keep looking into it.

> This was the existing functionality. It's probably worth making the override consistent with non-overridden coloring, i.e. your input can be any case and it will be cast to lower-case internally.

That seems to be how it works internally, for example you specify `'arachis ipaensis': 'green'` and then you can pass it 'Arachis ipaensis' and get green.

**Comment by svengato** [comment]
> In my ui.R, taxon-symbology-module.js (which imports taxonChroma from taxon-symbology.min.js) goes before phylogram.js, but for some reason it does not work.

If I change `type=module` to `type=text/javascript`, it loads first but gives the error "import declarations may only appear at top level of a module". If not, it loads later.

Tags like `async` and `defer` are available when loading JavaScript into HTML, but do not seem to be available in Shiny.

**Comment by svengato** [comment]
> Tags like `async` and `defer` are available when loading JavaScript into HTML, but do not seem to be available in Shiny.

I figured out a way to defer both scripts to the end, but the module still gets loaded last even though it is called first.

**Comment by svengato** [comment]
I eventually got it to work with Funnotate, and will go ahead and approve this, as both default and overridden colors work as expected.

**Review by svengato — APPROVED** [review]
Both default and overridden colors work as expected. My only suggestion is to mention (in `README.md`) that the taxon names to override should be in lower case.

**Comment by svengato** [comment]
> My only suggestion is to mention (in README.md) that the taxon names to override should be in lower case.

Probably no longer necessary, given your recent commit [bb47c03](https://github.com/legumeinfo/taxon-symbology/pull/10/commits/bb47c03634d91c69b0170710a815dfdcea30cd37).

**Comment by svengato** [comment]
One question: once you release `legumeinfo/taxon-symbology`, will we be able to load the module from its online home instead of from a local copy of `taxon-symbology.min.js`? This affects whether I add that file to the Funnotate repository - my inclination is to hold off for now.

**Comment by alancleary** [comment]
@svengato I'm glad to hear it's working. And sorry I forgot to mention that I updated the override API to be case-insensitive!

Yes, you'll be able to load the script from a CDN once it's published to NPM. I'll try and get it published tomorrow.

Thanks for the review!

**Comment by alancleary** [comment]
I've confirmed this works with GCV as well. Merging!

**Pull request merged**
